# 用于指示如何显示
# format = "\n\\$"

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

# 在命令字符旁显示一个字符,用于指示上一个命令是否执行成功
[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

# 用于显示上一条命令执行花了多久,时间毫秒
[cmd_duration]
min_time = 60000

[conda]
# symbol = " "
symbol = " "
ignore_base = false

[dart]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[git_status]
ahead = "⇡${count}(yellow)"
behind = "⇣${count}(yellow)"

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
format=""
disabled = true

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = ""
disable = true

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
